# Generated by Django 4.2.1 on 2024-02-09 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='contact',
            new_name='Contact',
        ),
    ]
